### ISSUE TITLE
Mouse gets stuck in a loop (sort of)

### ISSUE THREAD

**Issue by silws** [mazzzystar/QLearningMouse#2]
Hello,

It's true I modified the game a bit (the cheese moves to a wall when caught and there are multiple cheese pieces and the mouse wins after eating them all) but from what I remember this was an issue even before I modified it:

**After catching the cheese, the mouse gets stuck for about 300-500 moves on 2-4 blocks (it moves back and forth between them). After that, it progressively gets stuck for more and more moves...**

This doesn't happen if the mouse chooses a random action...is there any way that the reward remains the same in the cell even after the cheese moves? Although on update the mouse goes through the list of remaining cheese pieces and compares its cell with those cells only, so that shouldn't be the case...

I know it's a long shot but I thought maybe you had an idea 😁

Thanks

**Comment by mazzzystar** [comment]
"is there any way that the reward remains the same in the cell even after the cheese moves? "

What do you mean by "cheese move"?  
In general the multiple cheese game is a little bit different from current game, as the best solution has been changed.  And if a cheese was eaten by the mouse,  it will be generated in another randomly cell.

**Comment by silws** [comment]
By "moves" I mean it is generated in a wall cell (so it is left out of the game until the mouse eats all the cheese or the cat wins).
Do you have any pointers/advice/resources on how it is different? (I'm sorry if I'm asking for too much, I'm just a college student (who doesn't really like ML :( ) trying to do my homework)

Also, thank you so much for the quick response.

**Comment by mazzzystar** [comment]
The difference is that, the reward function for "winning the game" changed.
When there is only one best choice, the `q-learn` function is as below:
```
Q(s, a) += alpha * (reward(s,a) + gamma * max(Q(s', a') - Q(s,a))
```
But when there is multiple choices for "winning", you could have more than one `max(Q(s', a')`，and the mouse may get confused to choose next step. 

I'm also a new learner for reinforcement learning, so I've no idea on multiple target learning task. You may check [The Markov Decision Problem](http://ais.informatik.uni-freiburg.de/teaching/ss03/ams/DecisionProblems.pdf), which can help you learn the principle of MDP, which is the core of basic q-learning.

BTW, current reinforcement learning are CNN-based, which named "Deep Reinforcement Learning". You could check the "deep q-learning" from [PyTorch Tutorial](https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html).

**Comment by silws** [comment]
Ok, thanks a lot. Also, good job and thank you for the game :)
